### ISSUE TITLE
Google Top Bar

### ISSUE THREAD

**Issue by saravanabalagi** [DarkNightMode/Dark-Night-Mode-Chrome-Extension#32]
This is perhaps due to Google changing the styles recently, here's how google looks like when scrolled

![image](https://user-images.githubusercontent.com/8567893/63063554-12039380-bef5-11e9-8133-1744014964f9.png)

Expected the top bar to turn to dark mode

**Comment by saravanabalagi** [comment]
CSS needs to be 

```css
.minidiv .sfbg {
    background: black;
    box-shadow: 0 1px 6px 0 rgba(32,33,36,0.28);
    height: 72px;
    border-bottom: 1px solid rgba(255, 255, 255);
}
```

instead of 
```css
.minidiv .sfbg {
    background: white;
    box-shadow: 0 1px 6px 0 rgba(32,33,36,0.28);
    height: 72px;
}
```
